# What happens when you run the following program? Why do we get that result?

# def set_foo():
#     foo = 'bar'

# set_foo()
# print(foo)

You get an error because foo was defined within the scope of the function.